In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4175, 5511, 2814, 5645],
 [4175, 5511, 2814, 6789],
 [4175, 26, 2814, 3763],
 [2965, 383, 7515, 3365, 2730],
 [2965, 383, 7515, 3365, 5543],
 [5737, 4175, 5559, 2814, 6854],
 [3209, 3593, 9382, 3365]]

In [17]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4175 5511 2814 5645]
 [   0    0    0    0 4175 5511 2814 6789]
 [   0    0    0    0 4175   26 2814 3763]
 [   0    0    0 2965  383 7515 3365 2730]
 [   0    0    0 2965  383 7515 3365 5543]
 [   0    0    0 5737 4175 5559 2814 6854]
 [   0    0    0    0 3209 3593 9382 3365]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\jawed\anaconda3\envs\Data\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step


array([[[-4.38702591e-02,  4.75979112e-02,  6.15507364e-03,
          8.50383192e-03, -2.01708563e-02, -6.09619543e-03,
          4.84663509e-02,  3.18714716e-02, -5.16648218e-03,
         -2.16795448e-02],
        [-4.38702591e-02,  4.75979112e-02,  6.15507364e-03,
          8.50383192e-03, -2.01708563e-02, -6.09619543e-03,
          4.84663509e-02,  3.18714716e-02, -5.16648218e-03,
         -2.16795448e-02],
        [-4.38702591e-02,  4.75979112e-02,  6.15507364e-03,
          8.50383192e-03, -2.01708563e-02, -6.09619543e-03,
          4.84663509e-02,  3.18714716e-02, -5.16648218e-03,
         -2.16795448e-02],
        [-4.38702591e-02,  4.75979112e-02,  6.15507364e-03,
          8.50383192e-03, -2.01708563e-02, -6.09619543e-03,
          4.84663509e-02,  3.18714716e-02, -5.16648218e-03,
         -2.16795448e-02],
        [-4.70569506e-02,  3.67706530e-02, -1.07946396e-02,
          4.86002453e-02, -6.61940500e-03,  3.19537036e-02,
         -1.94256064e-02,  2.61860974e-02,  4.736248

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4175, 5511, 2814, 5645])